language: cpp
os: linux


git:
  submodules: false

env:
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    - os: osx
      compiler: clang
      node_js:
        - "stable"
      before_install:
        - set -e # Fail the whole script whenever any command fails
        - git submodule update --init --recursive

    - os: linux
      env: COMPILER=g++-4.8 CMAKE_OPTIONS="-DJSONCPP_LIB_BUILD_STATIC=ON -DJSONCPP_LIB_BUILD_SHARED=OFF"
      language: node_js
      before_install:
        - set -e
        - git submodule update --init --recursive
        - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
        - sudo apt-get install gcc-4.8 g++-4.8 libcap-dev
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
        - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
      node_js:
        - "stable"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - g++-4.8
            - nodejs
            - npm

script:
  - cd ${TRAVIS_BUILD_DIR}
  - npm --version
  - node --version
  - npm install
  - npm run conf
  - npm run rebuild
  - npm install jasmine-node
  - npm test
